
title: "DevLearnOps Blog"
author: "Manuel Castellin"
description: "DevLearnOps Blog" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

youtube_username: ManuelCastellin
github_username: "devlearnops"
facebook_username: devlearnops
#email: "example@mail.com"
#twitter_username: "twitteruser"
#linkedin_username: "linkedinuser"
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#googleplus_username: +username





# No change below this line!!
#
theme: jekyll-theme-cayman
